development:
  adapter: postgresql
  encoding: utf8
  database: tuutorials_Development
  host: localhost
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: tuutorials_Test
  host: localhost
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: tuutorials_Production
  host: localhost
  pool: 5
  username: 
  password:
