# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)

TechnologyCategory.create(:name => "Language")
TechnologyCategory.create(:name => "Web Framework")
TechnologyCategory.create(:name => "Tool")
TechnologyCategory.create(:name => "Software suit")
TechnologyCategory.create(:name => "Server-side")

ReportCategory.create(:name => "Tutorial")
ReportCategory.create(:name => "Comment")
ReportCategory.create(:name => "User")

Technology.create(:name => "ABAP", :technology_category_id => 1)
Technology.create(:name => "ActionScript", :technology_category_id => 1)
Technology.create(:name => "Ada", :technology_category_id => 1)
Technology.create(:name => "Alice", :technology_category_id => 1)
Technology.create(:name => "APL", :technology_category_id => 1)
Technology.create(:name => "Assembly", :technology_category_id => 1)
Technology.create(:name => "Awk", :technology_category_id => 1)
Technology.create(:name => "Bash", :technology_category_id => 1)
Technology.create(:name => "C", :technology_category_id => 1)
Technology.create(:name => "C#", :technology_category_id => 1)
Technology.create(:name => "C++", :technology_category_id => 1)
Technology.create(:name => "CFML", :technology_category_id => 1)
Technology.create(:name => "COBOL", :technology_category_id => 1)
Technology.create(:name => "Clojure", :technology_category_id => 1)
Technology.create(:name => "D", :technology_category_id => 1)
Technology.create(:name => "Delphi", :technology_category_id => 1)
Technology.create(:name => "Eiffel", :technology_category_id => 1)
Technology.create(:name => "Erlang", :technology_category_id => 1)
Technology.create(:name => "Forth", :technology_category_id => 1)
Technology.create(:name => "Fortran", :technology_category_id => 1)
Technology.create(:name => "Go", :technology_category_id => 1)
Technology.create(:name => "Groovy", :technology_category_id => 1)
Technology.create(:name => "Haskell", :technology_category_id => 1)
Technology.create(:name => "Java", :technology_category_id => 1)
Technology.create(:name => "JavaScript", :technology_category_id => 1)
Technology.create(:name => "LabVIEW", :technology_category_id => 1)
Technology.create(:name => "Lisp", :technology_category_id => 1)
Technology.create(:name => "Logo", :technology_category_id => 1)
Technology.create(:name => "Lua", :technology_category_id => 1)
Technology.create(:name => "MATLAB", :technology_category_id => 1)
Technology.create(:name => "ML", :technology_category_id => 1)
Technology.create(:name => "NXT-G", :technology_category_id => 1)
Technology.create(:name => "Objective-C", :technology_category_id => 1)
Technology.create(:name => "Pascal", :technology_category_id => 1)
Technology.create(:name => "Perl", :technology_category_id => 1)
Technology.create(:name => "PHP", :technology_category_id => 1)
Technology.create(:name => "Prolog", :technology_category_id => 1)
Technology.create(:name => "Python", :technology_category_id => 1)
Technology.create(:name => "R", :technology_category_id => 1)
Technology.create(:name => "RPG", :technology_category_id => 1)
Technology.create(:name => "Ruby", :technology_category_id => 1)
Technology.create(:name => "SAS", :technology_category_id => 1)
Technology.create(:name => "Scala", :technology_category_id => 1)
Technology.create(:name => "Scheme", :technology_category_id => 1)
Technology.create(:name => "Scratch", :technology_category_id => 1)
Technology.create(:name => "Smalltalk", :technology_category_id => 1)
Technology.create(:name => "SQL", :technology_category_id => 1)
Technology.create(:name => "Tcl", :technology_category_id => 1)
Technology.create(:name => "Visual Basic", :technology_category_id => 1)

Technology.create(:name => "CakePHP", :technology_category_id => 2)
Technology.create(:name => "Django", :technology_category_id => 2)
Technology.create(:name => "Ember.js", :technology_category_id => 2)
Technology.create(:name => "Play!", :technology_category_id => 2)
Technology.create(:name => "Rails", :technology_category_id => 2)
Technology.create(:name => "Sinatra", :technology_category_id => 2)
Technology.create(:name => "Spring", :technology_category_id => 2)
Technology.create(:name => "Symfony", :technology_category_id => 2)

Technology.create(:name => "Emacs", :technology_category_id => 3)
Technology.create(:name => "Photoshop", :technology_category_id => 3)
Technology.create(:name => "Vim", :technology_category_id => 3)

Technology.create(:name => "Android", :technology_category_id => 4)
Technology.create(:name => "iOS", :technology_category_id => 4)

Technology.create(:name => "Node.js", :technology_category_id => 5)


User.create!(:bio => "I am the creator", :email => "joe.d.forshaw@gmail.com", :password => "password", :password_confirmation => "password", :username => "Joe")
User.create!(:bio => "", :email => "forskei@hotmail.com", :password => "password", :password_confirmation => "password", :username => "Joe")

Tutorial.create(:name => "The Java Tutorials", :description => "The Java Tutorials are practical guides for programmers who want to use the Java programming language to create applications. They include hundreds of complete, working examples, and dozens of lessons. Groups of related lessons are organized into 'trails'.", :link => "http://docs.oracle.com/javase/tutorial/", :technology_id => Technology.find_by_name("Java").id, :user_id => User.find_by_username("Joe").id, :up_votes => 0, :down_votes => 0)
Tutorial.create(:name => "Java Tutorial - Tutorials Point", :description => "Java is a high-level programming language originally developed by Sun Microsystems and released in 1995. Java runs on a variety of platforms, such as Windows, Mac OS, and the various versions of UNIX. This tutorial gives a complete understanding on Java. This reference will take you through simple and practical approach while learning Java Programming language.", :link => "http://www.tutorialspoint.com/java/index.htm", :technology_id => Technology.find_by_name("Java").id, :user_id => User.find_by_username("Joe").id, :up_votes => 0, :down_votes => 0)
